apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: node:18
        workingDir: /app
        command: ["node", "index.js"]
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: firebase-secret
          mountPath: /app/file-4cacd-firebase-adminsdk-7d5di-0f4e2238db.json
          subPath: file-4cacd-firebase-adminsdk-7d5di-0f4e2238db.json
      volumes:
      - name: firebase-secret
        configMap:
          name: backend-config
          items:
          - key: FIREBASE_SERVICE_ACCOUNT
            path: file-4cacd-firebase-adminsdk-7d5di-0f4e2238db.json
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000